spring.application.name=pickeat-sse
spring.config.additional-location=classpath:/config/
spring.profiles.active=prod

spring.threads.virtual.enabled=true

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

pickeat.redis.channel=pickeat:updated
